services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: NODE_ENV=development pnpm install && NODE_ENV=production pnpm build
    startCommand: rsync -a public/ /data/public/ && pnpm start
    healthCheckPath: /_health
    autoDeploy: false
    rootDir: cms
    disk:
      name: strapi-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: ~22.14.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_FILENAME
        value: /data/strapi.db
      - key: HOST
        generateValue: 0.0.0.0
      - key: PORT
        generateValue: 80
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
